copy /b .\caves\BoulderDash01\Q .\caves\BoulderBonus\A
copy /b .\caves\BoulderDash01\R .\caves\BoulderBonus\B
copy /b .\caves\BoulderDash01\S .\caves\BoulderBonus\C
copy /b .\caves\BoulderDash01\T .\caves\BoulderBonus\D
copy /b .\caves\BoulderDash02\Q .\caves\BoulderBonus\E
copy /b .\caves\BoulderDash02\R .\caves\BoulderBonus\F
copy /b .\caves\BoulderDash02\S .\caves\BoulderBonus\G
copy /b .\caves\BoulderDash02\T .\caves\BoulderBonus\H
copy /b .\caves\BoulderDash03\Q .\caves\BoulderBonus\I
copy /b .\caves\BoulderDash03\R .\caves\BoulderBonus\J
copy /b .\caves\BoulderDash03\S .\caves\BoulderBonus\K
copy /b .\caves\BoulderDash03\T .\caves\BoulderBonus\L
copy /b .\caves\BoulderDashP1\Q .\caves\BoulderBonus\M
copy /b .\caves\BoulderDashP1\R .\caves\BoulderBonus\N
copy /b .\caves\BoulderDashP1\S .\caves\BoulderBonus\O
copy /b .\caves\BoulderDashP1\T .\caves\BoulderBonus\P
copy /b .\caves\ArnoDash01\Q .\caves\BoulderBonus\Q
copy /b .\caves\ArnoDash01\R .\caves\BoulderBonus\R
copy /b .\caves\ArnoDash01\S .\caves\BoulderBonus\S
copy /b .\caves\ArnoDash01\T .\caves\BoulderBonus\T