copy /b ..\caves_bin\BoulderDash01\Q ..\caves_bin\BoulderBonus\A
copy /b ..\caves_bin\BoulderDash01\R ..\caves_bin\BoulderBonus\B
copy /b ..\caves_bin\BoulderDash01\S ..\caves_bin\BoulderBonus\C
copy /b ..\caves_bin\BoulderDash01\T ..\caves_bin\BoulderBonus\D
copy /b ..\caves_bin\BoulderDash02\Q ..\caves_bin\BoulderBonus\E
copy /b ..\caves_bin\BoulderDash02\R ..\caves_bin\BoulderBonus\F
copy /b ..\caves_bin\BoulderDash02\S ..\caves_bin\BoulderBonus\G
copy /b ..\caves_bin\BoulderDash02\T ..\caves_bin\BoulderBonus\H
copy /b ..\caves_bin\BoulderDash03\Q ..\caves_bin\BoulderBonus\I
copy /b ..\caves_bin\BoulderDash03\R ..\caves_bin\BoulderBonus\J
copy /b ..\caves_bin\BoulderDash03\S ..\caves_bin\BoulderBonus\K
copy /b ..\caves_bin\BoulderDash03\T ..\caves_bin\BoulderBonus\L
copy /b ..\caves_bin\BoulderDashP1\Q ..\caves_bin\BoulderBonus\M
copy /b ..\caves_bin\BoulderDashP1\R ..\caves_bin\BoulderBonus\N
copy /b ..\caves_bin\BoulderDashP1\S ..\caves_bin\BoulderBonus\O
copy /b ..\caves_bin\BoulderDashP1\T ..\caves_bin\BoulderBonus\P
copy /b ..\caves_bin\ArnoDash01\Q ..\caves_bin\BoulderBonus\Q
copy /b ..\caves_bin\ArnoDash01\R ..\caves_bin\BoulderBonus\R
copy /b ..\caves_bin\ArnoDash01\S ..\caves_bin\BoulderBonus\S
copy /b ..\caves_bin\ArnoDash01\T ..\caves_bin\BoulderBonus\T